#!/bin/bash

echo ""
echo "Setting up."

wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh 
chmod +x Miniconda3-latest-Linux-armv7l.sh
./Miniconda3-latest-Linux-armv7l.sh

conda update conda
conda create --name py3 python=3
source activate py3

wget -O opencv.zip https://github.com/opencv/opencv/archive/3.2.0.zip
unzip opencv.zip

wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/3.2.0.zip 
unzip opencv_contrib.zip

pip install numpy

cd opencv-3.2.0/
mkdir build
cd build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=~/betabot/opencv_contrib-3.2.0/modules \
    -D PYTHON_EXECUTABLE=/home/odroid/miniconda3/envs/py3/bin/python \
    -D BUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON ..

make -j4

